serviceAccount:
  create: true

postgresql:
  postgresqlPassword: "admin"

configOverrides:
  secret: |
    SECRET_KEY = 'uptimelabs'

service:
  type: LoadBalancer
  port: 8088

bootstrapScript: |
  #!/bin/bash
  rm -rf /var/lib/apt/lists/* && \
  pip install \
    psycopg2-binary==2.9.1 \
    Authlib==1.2.0 \
    redis==3.5.3 && \
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
