apiVersion: v1
data:
  DNS_DOMAIN: localhost
  GIT_SSH_COMMAND: ssh -i /data/projects/.sshkeys/id_rsa
  KEYCLOAK_REALM: tenants
  KEYCLOAK_URL: keycloak-http.keycloak.svc.cluster.local
  LEX_BOT_LOCALE: en_GB
  MQTT_HOST: mosquitto.uptimelabs.svc.cluster.local
  MQTTHOST: mosquitto.uptimelabs.svc.cluster.local
  MYSQL_DATABASE: uptimelabs
  MYSQL_HOST: mysql.mysql.svc.cluster.local
  MYSQL_PORT: "3307"
immutable: false
kind: ConfigMap
metadata:
  name: uptimelabs-envs
  namespace: uptimelabs
