name: Lint and Test

on:
  pull_request:
    branches:
      - main

env:
  GOOS: linux
  GOARCH: amd64

jobs:
  lint-and-test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.20.0'

    - name: Test code
      run: |
        go test -v ./...
